#!/bin/bash

source methods.sh
source database.sh
source colors.sh

if [ ! $1 ]; then
    exit
fi

if [ ! -d /etc/kalu ]; then
    mkdir -p /etc/kalu
fi

DBPATH=/etc/kalu/kalu.db
initDB $DBPATH 

LOCAL_PKGS_DIR=$HOME/.packages
if [[ "$1" == "mkcache" ]]; then
    echo -e ${RED} "Making cache .. " ${RESTORE}
    # Go through the local packages.
    pkgFiles=$(find $LOCAL_PKGS_DIR -name "*.files")
    for pF in $pkgFiles; do
        insertintoDB $pF $DBPATH
    done
fi
