#define BUILD_HOST "localhost.localdomain"
#define BUILD_OS "Linux"
#define BUILD_PLATFORM "i686"
#define BUILD_KERNEL "2.6.32-431.5.1.el6.centos.plus.i686"
#define LA_PATH "/proc/loadavg"
#define BAT_NOW "/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0A:00/power_supply/BAT0/charge_now"
#define BAT_FULL "/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0A:00/power_supply/BAT0/charge_full"
#define BAT_STAT "/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0A:00/power_supply/BAT0/status"
#define LNK_PATH ""
#define BOX_SUSPEND " "
