#define BUILD_HOST "localhost.localdomain"
#define BUILD_OS "Linux"
#define BUILD_PLATFORM "i686"
#define BUILD_KERNEL "3.11.10-301.fc20.i686"
#define LA_PATH "/proc/loadavg"
#define BAT_NOW "/sys/devices/LNXSYSTM:00/device:00/PNP0C0A:00/power_supply/BAT0/charge_now"
#define BAT_FULL "/sys/devices/LNXSYSTM:00/device:00/PNP0C0A:00/power_supply/BAT0/charge_full"
#define BAT_STAT "/sys/devices/LNXSYSTM:00/device:00/PNP0C0A:00/power_supply/BAT0/status"
#define LNK_PATH ""
#define BOX_SUSPEND " "
